nome = input("Digite seu nome: ")
#print(nome)
idade = input("Digite a sua idade: ")
#print("O número digitado foi " + idade)
altura = float(input("Digite a sua altura em metros: "))
print("Seu nome é {}, sua idade é {} anos e você possui {:.2f}m".format(nome,idade,altura))